language: java
jdk: oraclejdk7

env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

script:
  - ./gradlew :plugin:test --info

branches:
  only:
    - develop

notifications:
  email: false

sudo: false
